#!/bin/bash

UPSMON_ENV=(
	DEADTIME FINALDELAY HOSTSYNC MINSUPPLIES MONITOR 
	NOCOMMWARNTIME POLLFAIL_LOG_THROTTLE_MAX NOTIFYCMD 
	NOTIFYMSG NOTIFYFLAG POLLFREQ POLLFREQALERT POWERDOWNFLAG 
	OFFDURATION RBWARNTIME RUN_AS_USER SHUTDOWNCMD SHUTDOWNEXIT 
	CERTPATH CERTIDENT CERTHOST CERTVERIFY FORCESSL DEBUG_MIN
)

if [ -z "$API_PASSWORD" ]
then
   API_PASSWORD=$(dd if=/dev/urandom bs=18 count=1 2>/dev/null | base64)
   echo "Generated API_PASSWORD: $API_PASSWORD"
fi

if [ -z "$ADMIN_PASSWORD" ]
then
   ADMIN_PASSWORD=$(dd if=/dev/urandom bs=18 count=1 2>/dev/null | base64)
   echo "Generated ADMIN_PASSWORD: $ADMIN_PASSWORD"
fi

if [ -z "$MONITOR" ]
then
   MONITOR="$UPS_NAME@localhost 1 monitor $API_PASSWORD master"
fi

# Can write or does not exist (support user defined mounted read-only configs)
if [ -w /etc/nut/ups.conf ] || [ ! -e /etc/nut/ups.conf ]; then
cat >/etc/nut/ups.conf <<EOF
[$UPS_NAME]
	desc = "$UPS_DESC"
	driver = $UPS_DRIVER
	port = $UPS_PORT
EOF
else
    echo "Skipped generation of ups.conf (user config is mounted)."
fi

# Can write or does not exist (support user defined mounted read-only configs)
if [ -w /etc/nut/upsd.conf ] || [ ! -e /etc/nut/upsd.conf ]; then
cat >/etc/nut/upsd.conf <<EOF
LISTEN $API_ADDRESS $API_PORT
EOF
else
    echo "Skipped generation of upsd.conf (user config is mounted)."
fi

# Can write or does not exist (support user defined mounted read-only configs)
if [ -w /etc/nut/upsd.users ] || [ ! -e /etc/nut/upsd.users ]; then
cat >/etc/nut/upsd.users <<EOF
[admin]
	password = $ADMIN_PASSWORD
	actions = set
	actions = fsd
	instcmds = all

[$API_USER]
	password = $API_PASSWORD
	upsmon master
EOF
else
    echo "Skipped generation of upsd.users (user config is mounted)."
fi

# Can write or does not exist (support user defined mounted read-only configs)
if [ -w /etc/nut/upsmon.conf ] || [ ! -e /etc/nut/upsmon.conf ]; then
	echo "# upsmon configuration generated by schmailzl/nut-upsd" > /etc/nut/upsmon.conf
	for env in "${UPSMON_ENV[@]}"; do
		echo "$env ${!env}" >> /etc/nut/upsmon.conf
	done

else
    echo "Skipped generation of upsmon.conf (user config is mounted)."
fi

if [ ! -d /dev/bus/usb ]; then
	echo "There is no USB device mapped to the container!"
	exit 1
fi

chgrp -R nut /etc/nut /dev/bus/usb

/usr/sbin/upsdrvctl start
/usr/sbin/upsd
exec /usr/sbin/upsmon -D
