#!/bin/bash

if [ -z "$PLATFORMS" ] || [[ $DOCKER_TAG = dev* ]]
then
  PLATFORMS="linux/arm64"
fi

docker buildx create --name multiarch --use
docker buildx build -t "$IMAGE_NAME" --platform "$PLATFORMS" --pull --push .
